### PR TITLE
Add missing completion for memory functions

### PR DESCRIPTION
**Pull request by gsouf**

### CODE REVIEW

**Review by Eforen — APPROVED** [review]
Thank you for your contributions to this tool

**Comment by gsouf** [comment]
👍

**Comment by Eforen** [comment]
Feel free to contribute more completions. I would continue but I don't play the game anymore but that's part of why I made this plugin for people is so that my investigations into the system could profit others that play later so it makes sense for it to be added to by those aswell :)

**Comment by gsouf** [comment]
ofcourse! :)

**Pull request merged**
